# Generated by Django 3.0.4 on 2020-03-26 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='gener',
            new_name='genre',
        ),
    ]
